version: '3.2'

services:

  mysql:
    image: mysql:5.7
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: library
      MYSQL_USER: student
      MYSQL_PASSWORD: student
      MYSQL_ROOT_PASSWORD: rootpw
    volumes: 
      - //C//Users//DockerFiles//sql:/docker-entrypoint-initdb.d
      - library_data:/var/lib/mysql      

  cdlibrarymgmt:
    image: testimage:latest
    ports:
      - 8080:8080
 
volumes:
  library_data: